CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL,
    "Role" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "DocumentOriginals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UploaderUserId" integer NOT NULL,
    "FilePath" character varying(500) NOT NULL,
    "OriginalFileName" character varying(255) NOT NULL,
    "FileSizeBytes" bigint NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    CONSTRAINT "PK_DocumentOriginals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentOriginals_Users_UploaderUserId" FOREIGN KEY ("UploaderUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TemplateRuleSets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    "JsonDefinition" text NOT NULL,
    "CreatedByUserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_TemplateRuleSets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TemplateRuleSets_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "DocumentProcessed" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SourceDocumentId" integer NOT NULL,
    "TemplateRuleSetId" integer NOT NULL,
    "FilePathFinalPdf" character varying(500) NOT NULL,
    "ExtractedJsonData" text NOT NULL,
    "ApprovedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "IsDeletedByClient" boolean NOT NULL,
    CONSTRAINT "PK_DocumentProcessed" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentProcessed_DocumentOriginals_SourceDocumentId" FOREIGN KEY ("SourceDocumentId") REFERENCES "DocumentOriginals" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_DocumentProcessed_TemplateRuleSets_TemplateRuleSetId" FOREIGN KEY ("TemplateRuleSetId") REFERENCES "TemplateRuleSets" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_DocumentOriginals_UploaderUserId" ON "DocumentOriginals" ("UploaderUserId");

CREATE INDEX "IX_DocumentProcessed_SourceDocumentId" ON "DocumentProcessed" ("SourceDocumentId");

CREATE INDEX "IX_DocumentProcessed_TemplateRuleSetId" ON "DocumentProcessed" ("TemplateRuleSetId");

CREATE INDEX "IX_TemplateRuleSets_CreatedByUserId" ON "TemplateRuleSets" ("CreatedByUserId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251103115812_AddIsDeletedByClientField', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "DocumentProcessed" ALTER COLUMN "TemplateRuleSetId" DROP NOT NULL;

ALTER TABLE "DocumentProcessed" ADD "GptContactInformation" text;

ALTER TABLE "DocumentProcessed" ADD "GptSummary" text;

ALTER TABLE "DocumentProcessed" ADD "GptTitle" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251104090820_AddGptFieldsToDocumentProcessed', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251104180028_MigrationName', '8.0.0');

COMMIT;

